// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"

	api "github.com/weavel-ai/promptmodel-go/api"
	core "github.com/weavel-ai/promptmodel-go/core"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Api *api.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL: options.BaseURL,
		caller:  core.NewCaller(options.HTTPClient),
		header:  options.ToHeader(),
		Api:     api.NewClient(opts...),
	}
}
